CREATE DATABASE library;
USE library;
CREATE TABLE books (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, title VARCHAR(255), author VARCHAR(255), category VARCHAR(255), tags VARCHAR(255), publisher VARCHAR(255), year INT, price INT);
CREATE TABLE users (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, username NOT NULL VARCHAR(255), password NOT NULL VARCHAR(255), name VARCHAR(255));
SELECT * FROM books;
SELECT * FROM users;